### ISSUE TITLE
dynamic created inputField with autocomplete

### ISSUE THREAD

**Issue by makeyos** [ideal-postcodes/ideal-postcodes-autocomplete#6]
how to address autocomplete suggestions to dynamic created inputFields

**Comment by cblanc** [comment]
The controller does not have to be instantiated when the page loads. It can be instantiated when your input fields are ready, you will need to know however the ids of the fields you wish to bind to.

i.e. if you're just binding to the main input field:

```javascript
const onInputFieldCreated = (inputId) => {
	return new IdealPostcodes.Autocomplete.Controller({
		api_key: inputId,
		inputField: "#input",
		outputFields: {
			line_1: "#line_1",
			line_2: "#line_2",
			line_3: "#line_3",
			post_town: "#post_town",
			postcode: "#postcode"
		}
	});
}
```

If you want to unbind the controller from the DOM, you can use `Controller#detachInterface` documented here: https://ideal-postcodes.github.io/ideal-postcodes-autocomplete/classes/autocomplete.controller.html#detachinterface

**Comment by makeyos** [comment]
Thank you for reply. 
I have managed to detach interface but it is removing DOM object completly.
And the most important I couldn't bind interface to the new input.

please take a look: https://jsfiddle.net/makeyos/s31uk86r/

**Comment by cblanc** [comment]
Hi there,

The `id`s in your new input/text entities are prefixed with an extra hash (`#`). If you amend your example with the lines below, that should get that fiddle working:

```
newEntry.find("input").attr("id", "search_field_" + i);
newEntry.find("textarea").attr("id", "result_field_" + i).html("");
```

**Comment by makeyos** [comment]
Stupid me.... 
Thank you.

**Comment by cblanc** [comment]
Hey, don't worry about. Glad to help. Let me know if you need anything else

**Comment by makeyos** [comment]
Thank you again. Have to admit the best you have support from similar products.
So maybe one more question :)

Any smart way to bind results to correct DOM object ? As you can see in my example all goes to the same one as it default is "result_field_" + i. Tried to handle (this) on controller response but "interface": { "input": } only sometimes provide details where the request is coming from.

Regards
