### ISSUE TITLE
Fill in address in the autocomplete field

### ISSUE THREAD

**Issue by garyk2015** [ideal-postcodes/ideal-postcodes-autocomplete#7]
Hi,

I am using the autocomplete function and it works well. However I notice by default when a user selects an address from the drop down it doesn't populate that field in the input field. I don't want to output the address lines to multiple other fields.

I just want to populate the field that has the autocomplete on it with the full address. Cant see any simple way of achieving this?

Thanks

Gary

**Comment by cblanc** [comment]
Hi Gary

Thanks for getting in contact. You can try hooking into the `onAddressRetrieved` callback to populate your input field, like so:

```javascript
new IdealPostcodes.Autocomplete.Controller({
  api_key: "iddqd",
  inputField: "#input",
  outputFields: {},
  onAddressRetrieved: address => {
    const input = document.getElementById("input");
    const output = ["line_1", "line_2", "line_3", "post_town", "postcode"]
      .map(elem => address[elem])       // Pick out address fields
      .filter(attribute => attribute !== ""); // Drop empty fields
    input.value = output.join(", ");
  }
});
```

Working demo here: http://jsfiddle.net/ideal_postcodes/t35px0a6/
